Repository OpMonTeam/OpMon, pull requests merged in 2019-03, with the labels that each got.

#90 Adding the in-game menu
  data/backgrounds/menu.png
  data/backgrounds/menuS1.png
  data/backgrounds/menuS2.png
  data/backgrounds/menuS3.png
  data/backgrounds/menuS4.png
  data/backgrounds/menuS5.png
  data/backgrounds/menuS6.png
  src/opmon/controller/GameMenuCtrl.cpp
  src/opmon/controller/GameMenuCtrl.hpp
  src/opmon/controller/OverworldCtrl.cpp
  src/opmon/controller/OverworldCtrl.hpp
  src/opmon/model/storage/GameMenuData.cpp
  src/opmon/model/storage/GameMenuData.hpp
  src/opmon/model/storage/OverworldData.cpp
  src/opmon/model/storage/OverworldData.hpp
  src/opmon/start/Gameloop.cpp
  src/opmon/view/Animations.cpp
  src/opmon/view/Animations.hpp
  src/opmon/view/GameMenu.cpp
  src/opmon/view/GameMenu.hpp
  src/utils/CycleCounter.hpp
Labels: enhancement, maximum priority, unverified

#91 Improved random number generation
  src/opmon/start/Gameloop.cpp
  src/utils/misc.cpp
  src/utils/misc.hpp
Labels: enhancement

#92 Battle improvement
  data/data/attacks.json
  data/keys/deutsch.rkeys
  data/keys/english.rkeys
  data/keys/espanol.rkeys
  data/keys/francais.rkeys
  src/opmon/controller/BattleCtrl.cpp
  src/opmon/controller/BattleCtrl.hpp
  src/opmon/model/objects/Attack.cpp
  src/opmon/model/objects/Attack.hpp
  src/opmon/model/objects/Attacks.cpp
  src/opmon/model/objects/Attacks.hpp
  src/opmon/model/objects/Turn.cpp
  src/opmon/model/objects/Turn.hpp
  src/opmon/view/Battle.cpp
  src/opmon/view/Battle.hpp
  src/opmon/view/Dialog.cpp
  src/opmon/view/Dialog.hpp
  src/utils/CycleCounter.hpp
Labels: enhancement, maximum priority
